name: CI (build & import)

on:
  workflow_dispatch:

jobs:
  build-smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Build wheel
        run: |
          python -m pip install -U pip build setuptools wheel
          python -m build

      - name: Inspect wheel has package files
        run: |
          python - <<'PY'
          import glob, zipfile
          whl = glob.glob("dist/*.whl")[0]
          print("Wheel:", whl)
          with zipfile.ZipFile(whl) as z:
            names = [n for n in z.namelist() if n.startswith("decision_security/")]
            print("Files in package:", len(names))
            assert len(names) > 0, "Wheel missing decision_security/*"
          PY

      - name: Install & import smoke
        run: |
          python -m pip install dist/*.whl
          python - <<'PY'
          from decision_security.synth import sample
          print("Smoke OK:", sample("poisson", 5, lam=1.0))
          PY